### ISSUE TITLE
Protocol Chrome error

### ISSUE THREAD

**Issue by baki250** [wilk/ng-websocket#11]
WebSocket connection to 'ws://apilocal.ws.com:8887/' failed: Error during WebSocket handshake: Sent non-empty 'Sec-WebSocket-Protocol' header but no response was received

Has anyone had this issue?

**Comment by n3gotium** [comment]
Could you update bower version with that fix, please. I have had to spent quite a time trying to figure out why websocket has stoped working after switching to the bower version.

**Comment by saurav2k4u** [comment]
I am using the bower version, and the error keeps coming up.

**Comment by Bclayson** [comment]
You can fix this by passing in "subprotocol: 'base46'".

Don't ask me why this works. It just does. Maybe someone can figure it out and make a pull request so that it works with the intended 'protocols' property. ::shrug::

**Comment by n3gotium** [comment]
Well, what I do in order to fix it is just passing an empty array to the "protocols" property.

**Comment by jfranki** [comment]
With two identical projects, the one with ng-websocket bower version 0.2.1 throws the error and the one with the actual git version works. Until the version is bumped the bower version is unusable at least in Chrome.

```javascript
me.$$ws = cfg.mock ? new $$mockWebsocket(cfg.mock, $http) : new WebSocket(cfg.url, cfg.protocols);
```

was changed to

```javascript
if (cfg.mock) {
    me.$$ws = new $$mockWebsocket(cfg.mock, $http);
}
else if (cfg.protocols) {
    me.$$ws = new WebSocket(cfg.url, cfg.protocols);
}
else {
    me.$$ws = new WebSocket(cfg.url);
}
```

**Comment by rudzikdawid** [comment]
Just put small change to your bower.json file:

  "dependencies": {
    "ng-websocket": "git://github.com/wilk/ng-websocket.git#master"
  }

now you have latest version in bower_components

**Comment by jcollum** [comment]
The fix for this (for me) was: `var ws = $websocket.$new({'url': 'ws://localhost:8000/foo', 'protocols': [], 'subprotocols': ['base46'] });`; subprotocols might not be needed...

**Comment by wilk** [comment]
This project is no longer mainteined. Sorry.
