### ISSUE TITLE
Exponential number of reconnects

### ISSUE THREAD

**Issue by everflux** [wilk/ng-websocket#17]
When trying to open the websocket and automatic reconnect is enabled, an exponential number of retries are taking place.

I believe this is due no checking if a close event is already part of a retry or not.
Clearing the reconnect interval-task before scheduling one fixes the issue: line 169

```
if (me.$$config.reconnect) {
                   if (me.$$reconnectTask) {
                        clearInterval(me.$$reconnectTask);
                        delete me.$$reconnectTask;
                    }
```

**Comment by deiucanta** [comment]
I can confirm this bug. @wilk can you fix it?

**Comment by cdupetit** [comment]
@wilk : There is a commit [here](https://github.com/wilk/ng-websocket/pull/15) to correct the bug.

**Comment by bojanbass** [comment]
Hi there, are there any plans to merge this fix into master?

**Comment by wilk** [comment]
This project is no longer mainteined. Sorry.
