### ISSUE TITLE
ERR_CONNECTION_REFUSED

### ISSUE THREAD

**Issue by OmarZeidan** [wilk/ng-websocket#20]
Hello, may anybody help with this error please ?

WebSocket connection to 'ws://localhost:12345/' failed: Error in connection establishment: net::ERR_CONNECTION_REFUSED

**Comment by cmacdonnacha** [comment]
+ 1

**Comment by Nazgard** [comment]
Are you sure about WebSocket Server is works?

**Comment by uberspeck** [comment]
I'm seeing the same issue. Web socket server is confirmed to be running, but can't connect in any browser

**Comment by wilk** [comment]
This project is no longer mainteined. Sorry.
