### ISSUE TITLE
update url in reconnect

### ISSUE THREAD

**Issue by fernandomoraes** [wilk/ng-websocket#26]
Threre is any way to update the URL during websocket reconection process? I basically need it because we provide a token in the URL during conection process, and this specific token is updated during application lifecycle, consequently we need to refresh it in the original URL

**Comment by anvial** [comment]
Hello, for me this is also interesting issue

**Comment by JustinSarwer** [comment]
I am also interested in this issue. It would be a very nice feature.

**Comment by wilk** [comment]
This project is no longer mainteined. Sorry.
