### ISSUE TITLE
server reject vs. losing connection

### ISSUE THREAD

**Issue by pliablepixels** [wilk/ng-websocket#28]
Hello, thanks for the excellent library.
I have the following question: I have implemented a form of authentication using this library - unless specific connection parameters are provided in the web socket URL the server rejects the connection.

This calls the on close event. The on close event is also called when there is a network disconnect or the server goes down. Is there any way to implement a differentiation between a server reject and a network loss? I know I can implement a solution where a server sends a message before disconnecting, but I am trying to avoid a bi-directional messaging system for now.

thanks

**Comment by fernandomoraes** [comment]
Hello, you can set a application status code on reject the connection on the server. The status codes between 4000 and 4999 are reserved to applications define own protocol.

See: https://tools.ietf.org/html/rfc6455#section-7.4

**Comment by pliablepixels** [comment]
Thank you - that looks perfect.
