### ISSUE TITLE
Project maintained ?

### ISSUE THREAD

**Issue by sushantdhiman** [wilk/ng-websocket#39]
Last commit was like 2 years ago

Thanks for your work on `ng-websocket`. I have been using `ng-websocket` for one of my project, It gets the work done but there are couple of issues me and others are facing, like....

- Exponential retires if socket connection is never established #17
- No `$destroy` method
- Need to use hacks to make things work #8, #37 

I will be happy to submit some PR to solve those issues if maintainer is willing to maintain the project actively.

cc @wilk

**Comment by wilk** [comment]
Not any more, sorry.
