### ISSUE TITLE
Socket $destroy

### ISSUE THREAD

**Issue by warmans** [wilk/ng-websocket#40]
Sometimes I have a socket that is specific to a "page" in a single page application. The user might not ever return to that page so when they leave I'd rather just close the socket and re-open it if they happen to return.

At the moment I have to do something like this since the websockets are stored globally: 

```
        var ws = $websocket.$new({url: wsURL, protocols:[]});
        $scope.$on("$destroy", function handler() {
            ws.$close();
            delete $websocket.$$websocketList[ws.$$config.url];
        });
```

It seems like there should just be a $destroy method in addition to $close so you can always safely call $new without weird stuff happening.

**Comment by wilk** [comment]
This project is no longer mainteined. Sorry.
